### PR TITLE
Require yuidoc code block type

### PR DESCRIPTION
**Pull request by knownasilya**
Thanks to @spikedkira for the help.

### CODE REVIEW

**Comment by knownasilya** [comment]
cc @locks it's a start to full codeblock parsing, which I'll probably do as a separate plugin, since it's generic enough.

**Comment by knownasilya** [comment]
@rwjblue

**Comment by rwjblue** [comment]
Seems good, can you add a test for the following:

\```app/foo/bar.js

**Comment by knownasilya** [comment]
Sure

**Comment by knownasilya** [comment]
Done @rwjblue

**Comment by knownasilya** [comment]
Ping @rwjblue

**Comment by knownasilya** [comment]
Ping again :)

**Review by locks — APPROVED** [review]

**Comment by rwjblue** [comment]
Thanks @knownasilya!

**Comment by rwjblue** [comment]
Published in 1.1.0.

**Pull request merged**
